name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
      - name: black Lint
        uses: psf/black@stable
      - name: flake8 Lint
        uses: py-actions/flake8@v2